export enum Edition {
  TROUBLE_BREWING = 'TROUBLE_BREWING',
  SECTS_AND_VIOLETS = 'SECTS_AND_VIOLETS',
  BAD_MOON_RISING = 'BAD_MOON_RISING',
  TRAVELLERS = 'TRAVELLERS',
  FABLED = 'FABLED',
  EXPERIMENTAL = 'EXPERIMENTAL',
}

export enum CharacterType {
  TOWNSFOLK = 'TOWNSFOLK',
  OUTSIDER = 'OUTSIDER',
  MINION = 'MINION',
  DEMON = 'DEMON',
}
